-- 재고 관리 시스템 DDL (PostgreSQL)
-- 애플리케이션은 spring.jpa.hibernate.ddl-auto=update로 기동 시 자동으로 스키마를 생성/갱신하므로
-- 별도로 이 스크립트를 실행하지 않아도 docker-compose + 애플리케이션 기동만으로 동작합니다.
-- 이 파일은 실제 운영되는 스키마를 명시적으로 문서화하기 위한 참고용입니다.

-- 상품(재고) 테이블
CREATE TABLE IF NOT EXISTS inventory (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255)             NOT NULL,
    quantity   INTEGER                  NOT NULL,
    created_at TIMESTAMP(6)             NOT NULL,
    updated_at TIMESTAMP(6)             NOT NULL,
    CONSTRAINT uk_inventory_name UNIQUE (name)
);

COMMENT ON TABLE inventory IS '상품';
COMMENT ON COLUMN inventory.id IS '재고 아이디';
COMMENT ON COLUMN inventory.name IS '상품명';
COMMENT ON COLUMN inventory.quantity IS '현재 재고 수량';
COMMENT ON COLUMN inventory.created_at IS '생성 시각';
COMMENT ON COLUMN inventory.updated_at IS '수정 시각';

-- 입출고 이력 테이블
CREATE TABLE IF NOT EXISTS inventory_history (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventory_id     BIGINT                   NOT NULL,
    type             VARCHAR(255)             NOT NULL CHECK (type IN ('INCREASE', 'DECREASE')),
    change_quantity  INTEGER                  NOT NULL,
    result_quantity  INTEGER                  NOT NULL,
    created_at       TIMESTAMP(6)             NOT NULL,
    updated_at       TIMESTAMP(6)             NOT NULL
);

COMMENT ON TABLE inventory_history IS '입출고 이벤트 이력';
COMMENT ON COLUMN inventory_history.id IS '이력 아이디';
COMMENT ON COLUMN inventory_history.inventory_id IS '대상 재고 아이디';
COMMENT ON COLUMN inventory_history.type IS '입고/출고 구분';
COMMENT ON COLUMN inventory_history.change_quantity IS '변경된 수량';
COMMENT ON COLUMN inventory_history.result_quantity IS '변경 후 남은 재고 수량';
COMMENT ON COLUMN inventory_history.created_at IS '생성 시각';
COMMENT ON COLUMN inventory_history.updated_at IS '수정 시각';

CREATE INDEX IF NOT EXISTS idx_inventory_history_inventory_id ON inventory_history (inventory_id);
